### ISSUE TITLE
[Google Maps Android API] Add map type selector

### ISSUE THREAD

**Issue by alexruperez** [Mun0n/MADBike#1]
Add a [map type selector](https://developers.google.com/maps/documentation/android-api/map) using the [Google Maps Android API](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#setMapType(int)).

![Map Type Selector](https://developers.google.com/maps/documentation/android-api/images/map_types_2x.png)

**Comment by esaezgil** [comment]
the project looks interesting to me, I'd like to add this over the next few days :)

**Comment by Mun0n** [comment]
Ok, I will take a look on that when my busy life let me do it! :-(
