### ISSUE TITLE
Tasks/refactors to be done?

### ISSUE THREAD

**Issue by aballano** [Mun0n/MADBike#4]
Hi there! 

First of all thanks for open sourcing the code, it's great to have more and more projects doing so. 

I want to start using the app and I might be interested in contributing to it in my free time (if possible), but I since there's no more issues created I took a look at the code and saw some possible suggestions, in case you're interested:

* There are some traces of mvp-ish here and there but nothing very solid or backed up by tests. Would that be a goal somehow? If so, maybe suggest an architecture (mvp, mvvm, mvi, any...)
* Convert some classes to Kotlin? This would also enable many other nice libs, like:
    * Anko: to faciltate view declaration via DSL (+ performance), easier management of intents and some other Android utils...
    * Coroutines or any lib based on them
    * Easier DI with [kodein](https://github.com/SalomonBrys/Kodein)
    * Functional programing (with [Kategory ](https://github.com/kategory/kategory) once it hits a stable version)
* Other async alternatives like rxjava, futures or anything based on kotlin coroutines.
* etc

**Comment by Mun0n** [comment]
I hope to have so much time to all of this stuff!!

 It sounds amazing, but i will need a lot of help and a lot of knowledge.

Thanks!
